[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

build_flags = -std=gnu++17
upload_protocol = jlink
debug_tool = jlink
debug_speed = 4000
debug_init_break = tbreak setup
build_type = debug

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3