
#ifndef ESP32_GAME_CONSOLE_GRAPHICS_H
#define ESP32_GAME_CONSOLE_GRAPHICS_H

#define SCREEN_CS        5
#define SCREEN_RST       16
#define SCREEN_DC        17

#define SCREEN_WIDTH 240
#define SCREEN_HEIGHT 320
#define MAP_BLOCK_SIZE 10

#endif //ESP32_GAME_CONSOLE_GRAPHICS_H
